version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  ruby: circleci/ruby@0.1.2 

workflows:
  heroku_deploy:
    jobs:
      - build
      #- hold:
      #    type: approval
      #    requires:
      - heroku/deploy-via-git:
          requires:
            - hold
          #filters:
          #  branches:
          #    only: sequential-branch-filter
              

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            sudo gem update --system
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
